services:
  users:
    image: postgres:15
    container_name: users
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    network_mode: "host" 

  pgadmin:
    image: 'docker.io/dpage/pgadmin4:latest'
    env_file:
      - ./.env
    ports:
      - 5444:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

volumes:
  pgadmin-data:
  postgres_data: